version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=wab#x%vPM4L6sq7u
    volumes:
      - db:/var/lib/postgresql/data
    network_mode: host
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    network_mode: host
  api:
    build: .
    network_mode: host
    depends_on:
      - db
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
      - spring_rabbitmq_port=5672
      - spring_rabbitmq_username=guest
    restart: always
networks:
  default_net:
    driver: bridge
volumes:
  db:
    driver: local
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local