version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=wab#x%vPM4L6sq7u
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_net
networks:
  rabbitmq_net:
    driver: bridge
volumes:
  db:
    driver: local